
= モノイド
ifndef::stem[:stem: latexmath]
ifndef::imagesdir[:imagesdir: ../img/]

++++
<style type="text/css">
p >code {background-color: #aaaaaa};　
td >code {background-color: #aaaaaa};
</style>
++++

モノイドは、理解するのが簡単、しかし奥が深く、モナドと同じかそれ以上に関数型プログラミングで応用局面もあり実用性が高いという、費用対効果（コスパ）抜群です。

だいたい、モナドを知りたいのなら、まずモノイドを知っておくべきなのは当たり前のことなのですが、ここまでモナド偏重でモノイドについてはあまり語られないのは、<<_モナドを理解するのが難しい理由>>の事情が原因です。

== 単位元

また、小学１年算数を復習すると、

[stem]
++++
1 + 1
++++

みたいな加算を最初に学びます。

子供というか、我々大人でも、脳は、すでに馴染みがある事象の延長・拡張でしか「理解する」というのは無理で、まず最初は、具体的な物質である「数え棒」「おはじき」を渡されて、徐々に数学的な抽象的概念に慣らされていきます。

どういう数学なのかというと、**（正の）自然数全体のなす加法の二項演算**ですよね。一番シンプルなパターンです。

このとき、 `+` は、**（正の）自然数全体** と組（ペア）となる**二項演算**としてしっかりと定義されています。

ところが、授業が進むにつれ様子が変わってきます。


---

https://ja.wikibooks.org/wiki/%E5%B0%8F%E5%AD%A6%E6%A0%A1%E7%AE%97%E6%95%B0/1%E5%AD%A6%E5%B9%B4#%E3%82%BC%E3%83%AD_0[**ゼロ 0**]

_1 から 1 を ひいた かず を ゼロ と いいます。 ゼロ は 0 と かきます。_

_0は、なにも、ない　かず です。_

_だから、 かず に 0 を たしても、 かわりません。_

_たとえば_

_7+0=7_
_「なな たす ゼロ は（わ） なな」です。_

---

[stem]
++++
7 + 0 = 7
++++


ゼロの発明は、数学史の飛躍の一つで、5世紀ごろのインド文明
で数字としてのゼロが発明されたのも数学が生まれてから2000年くらい経過した後ですし、ヨーロッパで広まったのは、中世を経てルネサンスのさらに後のニュートンの時代ですから、人類の数学史を考えると結構最近の発明だと言えます。

それなのに、さらっと小１の子供にゼロの概念をさも当たり前のように伝えるのですから、教育というものの凄まじさを実感するところですね。


**（正の）自然数全体** 

↓

**（ゼロを含む）自然数全体** 

としれっと拡張されてしまいました。

そして、ここで誤魔化されてはならないのが、同じ記号　`+` であっても、ゲームのルールが異なります。

**二項演算**というのは、必ず、演算対象と組（ペア）となってはじめて意味がある定義が成されるはずだったので、

**（正の）自然数全体のなす加法の二項演算**

↓

**（ゼロを含む）自然数全体のなす加法の二項演算**

と、二項演算も同時に更新されてしまいました。




こういう、「だから、 かず に 0 を たしても、 かわりません。」というような、演算で対象が不変になるような数のことを
https://ja.wikipedia.org/wiki/%E5%8D%98%E4%BD%8D%E5%85%83[
単位元]と言います。

---

> 数学、とくに抽象代数学において、単位元（たんいげん, 英: identity element）あるいは中立元（ちゅうりつげん, 英: neutral element）は、二項演算を備えた集合の特別な元で、ほかのどの元もその二項演算による単位元との結合の影響を受けない。

https://ja.wikipedia.org/wiki/%E5%8D%98%E4%BD%8D%E5%85%83[
単位元]

---

[WARNING]
.単位元を表す記号
====
「単位元」は、**identity element**から、

- identity
- e

あるいは「中立元」**neutral element**の頭文字**n**に似ている（と筆者は思っている）

- η　（エータ、イータ、イタ）

と表記されることが多いですが、本稿では、とっつきやすさを重視して、

**e**と表記することにします。

ただし、後々まったく同じ数学的対象なのに、後から、単位元のことを、identityと書かれたり、ηと書かれたり、場合によっては `unit` だの　`return`　だの本質ではないところの用語の使い回しで、モナド界隈特有の混乱を極めるので、それは心の準備が必要です。
====




加法の単位元 `e` は `0` ですが、
[stem]
++++
7 + 0 = 7
++++

乗法の単位元 `e` は `1` となります。
[stem]
++++
7 \times 1 = 7
++++

文字列の単位元 `e` は `""`  となります。
[stem]
++++
"Hello" + "" = "Hello"
++++

そして、こういう正の自然数に更に「ゼロの後乗せ」してゼロを含む自然数に拡張する、同時に組（ペア）になっている二項演算子も更新することを、単位元の添加と言います。 

---

_**単位元の添加**_

_マグマ (M, ∗) が与えられたとき、M に M のどの元とも異なる新たな元 1 を付け加えた集合 M1 := M ∪ {1} で_

_任意の a ∈ M1 に対して a * 1 = 1 * a = a_
_と定めて、M の演算 ∗ を M1 上に延長することにより、元 1 を M1 の ∗ に関する単位元とすることができる。この (M1, ∗) を (M, ∗) の 1-添加という。_

_もし、M がもともと ∗ に関する単位元 e を持っていたとしても、e は M1 上ではもはや ∗ に関する単位元ではない。_

https://ja.wikipedia.org/wiki/%E5%8D%98%E4%BD%8D%E5%85%83#%E6%80%A7%E8%B3%AA[単位元#性質]

---


[TIP]
.sds
====
dfgdf
====


マグマ (M, ∗)に、単位元 e が最初からあるとき、あるいは、正の自然数の二項演算に単位元0 を後から添加してゼロを含む自然数の二項演算とするようなときは、eを加えて、

単位的マグマ

[stem]
++++
(M,e,∗) 
++++

と書くことにしましょう。

組（ペア）から３つ組（トリプル）になったのがポイントです。

具体的な二項演算が定まったときは、

[stem]
++++
(自然数,0,+) 
++++

[stem]
++++
(自然数,1,\times) 
++++

[stem]
++++
(文字列,"",+) 
++++

というようになります。

マグマ(M, ∗) はオブジェクトとメソッドの組として変換できるので、自然数全体:Mのメンバーである特定の値:mで、


[stem]
++++
e + m = m = m + e
++++

[stem]
++++
e.plus(m) = m = m.plus(e) 
++++
 
ｆ


1 + 2 + 5 + 9
